@startuml
skinparam defaultFontName Arial

title Identifying mCODE Patients: Conditions-then-patients approach
hide footbox
participant "mCODE Data Receiver" as Receiver
participant "mCODE Data Sender" as Sender

group Get Conditions, then Patients
    "Receiver" -> "Sender" : ""GET [base]/Condition?code:in=...""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Conditions
    ...
    note over Receiver
    Receiver extracts unique
    patient IDs from Conditions to
    generate a second request:
    end note
    "Receiver" -> "Sender" : ""GET [base]/Patient?_id=id_1,id_2,...,id_n""
    "Sender" --> "Receiver" : HTTP response containing Bundle of Patients
end


@enduml
