@startuml
skinparam defaultFontName Arial

title mCODE Patients: Pull Model
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

group Get Patients via ""_profile""
    "Receiver" -> "Sender" : ""GET [base]/Patient?_profile=...mcode-cancer-patient""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Patients
end

group Get Conditions, then Patients
    "Receiver" -> "Sender" : ""GET [base]/Condition?code:in=...""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Conditions
    ...
    note over Receiver
    Repeat for each Patient
    identified in previous request
    end note
    "Receiver" -> "Sender" : ""GET [base]/Patient/[id]""
    "Sender" --> "Receiver" : HTTP response containing Patient
end

group Get Conditions with Patients
    "Receiver" -> "Sender" : ""GET [base]/Condition?code:in=...&_include=Condition:subject""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Conditions and Patients
end

group Get Patients via reverse chaining
    "Receiver" -> "Sender" : ""GET [base]/Patient?_has:Condition:subject:code:in=...""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Patients
end

@enduml
