@startuml
skinparam defaultFontName Arial

title Retrieving an mCODE Patient Bundle
hide footbox
participant "mCODE Data Receiver" as Receiver
participant "mCODE Data Sender" as Sender
"Receiver" -> "Sender" : ""GET [base]/Patient/[id]/$mcode-everything""
"Sender" --> "Receiver" : HTTP response containing mCODE Patient Bundle
@enduml
