@startuml
skinparam defaultFontName Arial

title mCODE Patients: Pull Model - Implementation Option 1 (Preferred)
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

group Get Patients via ""_profile""
    "Receiver" -> "Sender" : ""GET [base]/Patient?_profile=...mcode-cancer-patient""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Patients
end


@enduml
