@startuml
skinparam defaultFontName Arial

title mCODE Patient
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

group Get Patients
    "Receiver" -> "Sender" : ""GET [base]/Patient/[id]""
    "Sender" --> "Receiver" : HTTP response containing Patient resource
end


@enduml
