@startuml
skinparam defaultFontName Arial

title mCODE Patients: Push Model
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

"Sender" -> "Receiver" : ""POST [base]/Patient"" or\n""PUT [base]/Patient/[id]""

note left
Request body contains
a Patient resource
conforming to CancerPatient
end note

@enduml
