@startuml
skinparam defaultFontName Arial

title mCODE Patient Bundle: Pull Model
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver
"Receiver" -> "Sender" : ""GET [base]/$mcode-patient-bundle""
"Sender" --> "Receiver" : HTTP response containing mCODE Patient Bundle
@enduml
