@startuml
skinparam defaultFontName Arial

title mCODE Patient Bundle: Push Model
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

"Sender" -> "Receiver" : ""POST [base]/Bundle"" or\n""PUT [base]/Bundle/[id]""
note left
Request body contains
an mCODE Patient Bundle
end note

@enduml
