@startuml
skinparam defaultFontName Arial

title mCODE Patients: Pull Model - Implementation Option 2.1 (Fallback)
hide footbox
participant "mCODE Data Sender" as Sender
participant "mCODE Data Receiver" as Receiver

group Get Patients via reverse chaining
    "Receiver" -> "Sender" : ""GET [base]/Patient?_has:Condition:subject:code:in=...""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Patients
end

@enduml
