@startuml
skinparam defaultFontName Arial

title Identifying mCODE Patients: Patients-with-cancer-condition approach
hide footbox
participant "mCODE Data Receiver" as Receiver
participant "mCODE Data Sender" as Sender

group Get Patients via reverse chaining
    "Receiver" -> "Sender" : ""GET [base]/Patient?_has:Condition:subject:code:in=...""
    "Sender" --> "Receiver" : HTTP response containing Bundle of relevant Patients
end

@enduml
