// Code Systems
Alias:   LNC = http://loinc.org
Alias:   SCT = http://snomed.info/sct
Alias:   UCUM = http://unitsofmeasure.org
Alias:   NCIT = http://ncithesaurus-stage.nci.nih.gov
Alias:   ICD10CM = http://hl7.org/fhir/sid/icd-10-cm
Alias:   ICDO3 = http://terminology.hl7.org/CodeSystem/icd-o-3
Alias:   RXN = http://www.nlm.nih.gov/research/umls/rxnorm
Alias:   CPT = http://www.ama-assn.org/go/cpt
Alias:   AJCC = http://cancerstaging.org
Alias:   GTR = http://www.ncbi.nlm.nih.gov/gtr
Alias:   CLINVAR = http://www.ncbi.nlm.nih.gov/clinvar
Alias:   IDTYPE = http://terminology.hl7.org/CodeSystem/v2-0203
Alias:   HGNC = http://www.genenames.org   // changed by MK 10-19-2020 to align with FHIR (see https://www.hl7.org/fhir/terminologies-systems.html)
Alias:   HGVS = http://varnomen.hgvs.org
Alias:   SPTY = http://terminology.hl7.org/CodeSystem/v2-0487
Alias:   CondCat = http://terminology.hl7.org/CodeSystem/condition-category
Alias:   ClinStatus = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias:   VerStatus = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias:   ObsCat = http://terminology.hl7.org/CodeSystem/observation-category
Alias:   ObsInt = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias:   DiagnosticService = http://terminology.hl7.org/CodeSystem/v2-0074
Alias:   OmbRaceCat = urn:oid:2.16.840.1.113883.6.238
Alias:   TimingAbbreviation = http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation
Alias:   MedRequestStatus = http://hl7.org/fhir/CodeSystem/medicationrequest-status 
Alias:   MedRequestIntent = http://hl7.org/fhir/CodeSystem/medicationrequest-intent
Alias:   MedCat = 	http://terminology.hl7.org/CodeSystem/medicationrequest-category
Alias:   RefMeaning = http://terminology.hl7.org/CodeSystem/referencerange-meaning