Instance: scenario1-mcode-patient-bundle
InstanceOf: MCODEPatientBundle
Description: "Extended example 1 as a mCODE Patient Bundle"
// Named slices, required
* entry[cancerPatient].resource = scenario1-mcode-cancer-patient
* entry[cancerPatient].fullUrl = "http://example.org/fhir/Patient/scenario1-mcode-cancer-patient"
* entry[primaryCancerCondition].resource = scenario1-mcode-primary-cancer-condition
* entry[primaryCancerCondition].fullUrl = "http://example.org/fhir/Condition/scenario1-mcode-primary-cancer-condition"
// Other slices
* entry[2].resource = scenario1-mcode-cancer-disease-status
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-cancer-disease-status"
* entry[+].resource = scenario1-mcode-cancer-genetic-variant
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-cancer-genetic-variant"
* entry[+].resource = scenario1-mcode-cancer-genomics-report
* entry[=].fullUrl = "http://example.org/fhir/DiagnosticReport/scenario1-mcode-cancer-genomics-report"
* entry[+].resource = scenario1-mcode-cancer-related-surgical-procedure-mastectomy
* entry[=].fullUrl = "http://example.org/fhir/Procedure/scenario1-mcode-cancer-related-surgical-procedure-mastectomy"
* entry[+].resource = scenario1-teleradiotherapy-prescription-delivery
* entry[=].fullUrl = "http://example.org/fhir/Procedure/scenario1-teleradiotherapy-prescription-delivery"
* entry[+].resource = scenario1-mcode-tnm-clinical-stage-group
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tnm-clinical-stage-group"
* entry[+].resource = scenario1-mcode-tnm-primary-tumor-category
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tnm-primary-tumor-category"
* entry[+].resource = scenario1-mcode-tnm-clinical-regional-nodes-category
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tnm-clinical-regional-nodes-category"
* entry[+].resource = scenario1-mcode-tnm-clinical-distant-metastases-category
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tnm-clinical-distant-metastases-category"
* entry[+].resource = scenario1-mcode-genetic-specimen
* entry[=].fullUrl = "http://example.org/fhir/Specimen/scenario1-mcode-genetic-specimen"
* entry[+].resource = scenario1-mcode-genomic-region-studied
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-genomic-region-studied"
* entry[+].resource = scenario1-mcode-ecog-performance-status
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-ecog-performance-status"
* entry[+].resource = scenario1-mcode-tumor-marker-test-er
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tumor-marker-test-er"
* entry[+].resource = scenario1-mcode-tumor-marker-test-pr
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tumor-marker-test-pr"
* entry[+].resource = scenario1-mcode-tumor-marker-test-her2
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tumor-marker-test-her2"
* entry[+].resource = scenario1-mcode-tumor-marker-test-oncotype-dx
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-tumor-marker-test-oncotype-dx"
* entry[+].resource = scenario1-mcode-cancer-related-medication-chemo-doxorubicin
* entry[=].fullUrl = "http://example.org/fhir/MedicationRequest/scenario1-mcode-cancer-related-medication-chemo-doxorubicin"
* entry[+].resource = scenario1-mcode-cancer-related-medication-chemo-cyclophosphamide
* entry[=].fullUrl = "http://example.org/fhir/MedicationRequest/scenario1-mcode-cancer-related-medication-chemo-cyclophosphamide"
* entry[+].resource = scenario1-mcode-cancer-related-medication-chemo-paclitaxel
* entry[=].fullUrl = "http://example.org/fhir/MedicationRequest/scenario1-mcode-cancer-related-medication-chemo-paclitaxel"
* entry[+].resource = scenario1-mcode-cancer-related-medication-anastrozole
* entry[=].fullUrl = "http://example.org/fhir/MedicationRequest/scenario1-mcode-cancer-related-medication-anastrozole"
* entry[+].resource = scenario1-mcode-cancer-related-elixhauser-comorbidities
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-mcode-cancer-related-elixhauser-comorbidities"
* entry[+].resource = scenario1-body-weight
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-body-weight"
* entry[+].resource = scenario1-neutrophils
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-neutrophils"
* entry[+].resource = scenario1-organization1-mcode
* entry[=].fullUrl = "http://example.org/fhir/Organization/scenario1-organization1-mcode"
* entry[+].resource = scenario1-us-core-smoking-status
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-us-core-smoking-status"
* entry[+].resource = scenario1-us-core-procedure-biopsy
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-us-core-procedure-biopsy"
* entry[+].resource = scenario1-us-core-procedure-mammogram
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-us-core-procedure-mammogram"
* entry[+].resource = scenario1-family-member-history-aunt
* entry[=].fullUrl = "http://example.org/fhir/FamilyMemberHistory/scenario1-family-member-history-aunt"
* entry[+].resource = scenario1-us-core-procedure-mammogram
* entry[=].fullUrl = "http://example.org/fhir/Procedure/scenario1-us-core-procedure-mammogram"
* entry[+].resource = scenario1-family-member-history-uncle
* entry[=].fullUrl = "http://example.org/fhir/FamilyMemberHistory/scenario1-family-member-history-uncle"
* entry[+].resource = scenario1-diagnosticreport-pathology
* entry[=].fullUrl = "http://example.org/fhir/DiagnosticReport/scenario1-diagnosticreport-pathology"
* entry[+].resource = scenario1-observation-smoking-history
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-diagnosticreport-pathology"
* entry[+].resource = scenario1-observation-tumor-invasion-negative
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-observation-tumor-invasion-negative"
* entry[+].resource = scenario1-observation-tumor-negative-margins
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-observation-tumor-negative-margins"
* entry[+].resource = scenario1-observation-tumor-sentinel-nodes
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-observation-tumor-sentinel-nodes"
* entry[+].resource = scenario1-observation-tumor-size
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-observation-tumor-size"
* entry[+].resource = scenario1-observation-tumor-dcis
* entry[=].fullUrl = "http://example.org/fhir/Observation/scenario1-observation-tumor-dcis"
* entry[+].resource = scenario1-us-core-practitioner
* entry[=].fullUrl = "http://example.org/fhir/Pracititioner/scenario1-us-core-practitioner"
* entry[+].resource = scenario1-practitioner2-mcode
* entry[=].fullUrl = "http://example.org/fhir/Pracititioner/scenario1-practitioner2-mcode"

